# Generated by Django 4.2 on 2025-04-08 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('especialidade', models.CharField(choices=[('PED', 'Pediatra'), ('CAR', 'Cardiologista'), ('NEU', 'Neurologista'), ('CLG', 'Clínico Geral')], max_length=3)),
                ('crm', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('status', models.CharField(choices=[('AGE', 'Agendado'), ('REA', 'Realizado'), ('CAN', 'Cancelado')], max_length=3)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
            ],
        ),
    ]
