# Generated by Django 4.2 on 2025-04-08 14:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_alter_medico_crm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='crm',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Formato do CRM inválido. Use XX/XXXXX', regex='^\\d{2}/\\d{5}$')]),
        ),
    ]
